### ISSUE TITLE
proposal: dark mode

### ISSUE THREAD

**Issue by iuioiua** [iuioiua/bxnch#7]
See [docs](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to). I'm thinking we can do this via a `dark` URL query.

**Comment by lino-levan** [comment]
Not super easy, but not super difficult. We just have to change a lot of things to "white" if the dark URL query param is set.
